### PR TITLE
Bump deps and SDK constraint to version solve in dart2

### PR DESCRIPTION
**Pull request by nshahan**

### CODE REVIEW

**Comment by nshahan** [comment]
I'm guessing this is the branch that you publish the dart2 version from.

**Review by nex3 — APPROVED** [review]

**Comment by kevmoo** [comment]
We'll have to update travis for each branch so it runs on the right SDK!

**Comment by nshahan** [comment]
@kevmoo Not sure what to do at this point before there is a released version of the SDK. Are you saying we should commit?
```
dart:
  - stable/raw/2.0.0
```

**Comment by kevmoo** [comment]
Leave it as `- dev` for now. We'll do the big all migration of most of
these on Monday+

**Comment by nshahan** [comment]
Shoot, I didn't notice that the dart2 branch is behind a published release. I'm going to make a new PR to make sure I'm including those commits.

**Pull request closed without merging**
